It's ALIVE
TauCetiStation/Rules pull request #13
Opened 2018-10-05 11:04 UTC by EdlerN

В общем, да. Написал наконец-то более ли менее вменяемую основу. Забыл про ксеноту и кажется про сумасшествие и прочие психические отклонения, но это можно добавить чуть позже. Пока что хочется выложить вот это на обсуждение.

2018-10-05 11:07 UTC, volas commented on rules.md
> +## Общие правила сообщества
это как раз хотели выпилить и оставить конкретно правила сервера, по необходимости отдельно дискорда/форума, тк по фидбеку текущие запутанны

2018-10-05 11:08 UTC, EdlerN commented on rules.md
> +## Общие правила сообщества
Там рул ноль который распространяется на все в принципе. Можно, разумеется, это как-то иначе завернуть.

2018-10-05 11:27 UTC, Belfogor commented
> Написание жалоб тоже стоит отложить до окончания раунда  

Буквально же воспримут, и будут топить АХ в конце раунда. Ну и еще ты забыл упомянуть об использование мультиаккаунтов. 

А так правила написаны хорошо. Даже доебаться не к чему.

2018-10-05 11:30 UTC, EdlerN commented
Это надо поправить. Тут имеется в виду написание жалоб на форум. На счет мультиаккаунтов есть десятый пункт основных правил.

2018-10-05 11:41 UTC, Belfogor commented
Хотя мне опять таки не очень нравится, что пунктом 4.1, правил персонажа, ты легализируешь метагейм. Я все таки думаю что стоит исходить из того, что отсутствие кого-либо или чего-либо на станции, это лишь очередное обстоятельство, которое может послужить дальнейшим толчком для развития внутриигровых событий, или препятствие, которое следует обходить доступными твоему персонажу путями. 

А если проще. Отсутствие генетика может дать повод организовать похоронную процессию, со всеми вытекающими. 
А отсутствие врачей лицезреть истекающего кровью товарища, с ощущением безысходности и злости за свою беспомощность, но никак не поводом прооперировать его.

2018-10-05 11:44 UTC, EdlerN commented
С этим нашим метагеймом было слишком много проблем и головной боли как для игроков так и для админов. 
И да. Я не заставляю игроков метагеймить. Я оставляю использование дополнительных знаний и навыков на их усмотрение. За исключением случаев, когда это напрямую вредит другим.

2018-10-05 12:53 UTC, Avatar4 commented
Нужно добавить конкретики в правила про ерп. Что считается допустимым а что уже переходит грань. Да и то что персонал пришел сюда не шлёпать задницы и выводить тонны текста в me как Эймзы

2018-10-05 12:54 UTC, EdlerN commented
Вообще, у меня просто предложение это смержить а там уже каждый может дополнять то что ему захочется. Кто-то вроде бы уже вызывался про ЕРП расписать подробнее.

2018-10-05 13:33 UTC, dred1792 requested changes

2018-10-05 13:33 UTC, dred1792 commented on rules.md
> +3.2 Распространение любой информации о текущем раунде посредством любых OOC средств запрещено. Сюда попадает как игровой OOC канал, так и любые сторонние форумы/чаты. Информация и ее распространение
В конце "очень часто может повлиять всех участников.", думаю тут потерялась частица "на".

2018-10-05 13:42 UTC, dred1792 commented
В общем и целом, мне нравится.

2018-10-19 21:48 UTC, volas commented on rules.md
> +2. Поведение, направленное на намеренное причинение вреда другим игрокам без малейших на то игровых оснований, не приветствуется вплоть до выдачи перманентной блокировки без лишних разговоров
Частично пересекается с рул 0 по смыслу

2018-10-19 21:48 UTC, volas commented on rules.md
> +3.2.1 Если у вас возникли какие-то проблемы с механикой - напишите менторам (кнопка F9) если вы считаете, что обнаружили баг - напишите Администраторам (F1), если вы уверены что нашли баг - можете на
Немного странно, что это подпункт правила о метагейме, так как касается довольно косвенно

2018-10-19 21:48 UTC, volas commented on rules.md
> +1.1 Соблюдайте нормы русского языка - пишите грамотно.
Я Белфа уже ругал за хардкод нумерации - чуть что, придётся везде вручную переделывать. Лучше использовать для этого маркдаун разметку, нумерованную или нет.

2018-10-19 21:48 UTC, volas commented on rules.md
> +3.1 Сюда относится игра с использованием сторонних чатов (голосовых или текстовых) для кооперации действий. Никто не будет устраивать охоту на ведьм, но когда один персонаж бежит через пол станции чт
Возможно стоит по смыслу разделять подпункт правила и пояснения к нему.
Если, допустим, смотреть 1.2.1 или 1.3 - это вполне самостоятельные пункты, по которым можно наказывать.
Тут 3.1, 3.1.1 -  скорее пояснения.

2018-10-19 21:48 UTC, volas commented on rules.md
> +3. Метагейминг - использование информации, полученной неигровым путем (Из любого OOC источника), для получения каких-либо игровых преимуществ серьезно вредит игровой атмосфере и потому запрещено.
Довольно большой раздел о метагейме получился. Можно подкорректировать/сократить без потери смысла, но не критично для мержа  - это потом можно доправить.

2018-10-19 21:48 UTC, volas commented on rules.md
> +4.3 Если Администратор просит вас немного умерить свой пыл, ссылаясь на это правило - скорее всего вы делаете что-то не так.
излишне, это к любому пункту относится

2018-10-19 21:48 UTC, volas commented on rules.md
> +5.1 Да, на дворе 25** год и ваш персонаж вполне может знать о событиях на земле 21-го века, но это совершенно не повод начинать орать имена известных политических деятелей того периода в радио. Или п
:+1:

2018-10-19 21:48 UTC, volas commented on rules.md
> +5.1.1 Есть небольшое исключение. К примеру, обмен ссылками на какую-нибудь музыку через ПДА, в случае если вы замените название сайта на что-то более подходящее для этой вселенной (тот же wetskrells.
Нету смысла меняться ссылками, если для этого нужно ломать ссылку. Можно обозначить конкретнее про допустимость обмена ссылками на ютубы/вики через текстовую, не голосовую, инфу, вида ПДА.

Где-то тут можно наверно еще вспомнить про ic say скобочки и эмоджи

2018-10-19 21:48 UTC, volas commented on rules.md
> +5.2 Политические и религиозные дебаты в ооц под запретом. Это те самые темы, которые, зачастую, приводят к конфликтам, которые никто не хочет разрешать. А как следствие - переход на личности и оскорб
слабо относится к **5**. Если основной пункт про нарушение ic атмосферы, то это - про флейм и OOC

2018-10-19 21:48 UTC, volas commented on rules.md
> +8. Любой nsfw контент вне специально отведенных под это мест (как то - nsfw каналы дискорда) под запретом
```suggestion
8. Порнографический или любой другой NSFW ("Not Safe For Work" или "не безопасный для работы" - не приемлемый в приличном обществе) контент под запретом
```

Это планируется строго как игровые правила, дискорд тут лишнее. Лучше просто запретить. Еще какое-то более подробное описание бы...

2018-10-19 21:48 UTC, volas commented on rules.md
> +9. Эта игра про взрослых людей, в которой достаточно часто могут всплывать весьма взрослые темы. Потому, если вам еще нет 16 лет - настоятельно рекомендуем вам покинуть сообщество.
```suggestion
9. Игра предназначена для лиц старше 16 лет. Если ваш возраст не соответствует - немедленно закройте игру.
```

Строгость законов компенсируется необязательностью...

2018-10-19 21:48 UTC, volas commented on rules.md
> +10. Администрация оставляет за собой право переносить баны с других серверов и принимать меры по отношению к тем, кто пытается обходить уже имеющиеся у них баны.
"других" звучит довольно многозначно, будто мы базу анимусов можем скопировать. Текущая формулировка в /rules мне нравится больше.

Еще, свалены в одну корзину правила о переносе банов и обходе банов - это довольно разные вещи по смыслу

2018-10-19 21:48 UTC, volas commented on rules.md
> +5. Флавор существует сугубо для описания внешности персонажа. Нет, серьезно. Не стоит писать туда историю получения воон того шрама. Даже если очень хочется. Ведь другим будет намного интереснее узна
```suggestion
5. Флавор существует сугубо для описания внешности персонажа. Нет, серьезно. Не стоит писать туда историю получения воон того шрама. Или описывать характер персонажа. Даже если очень хочется. Ведь другим будет намного интереснее узнать это всё от вашего персонажа, а не просто прочитать где-то. 
```
как-то так может

2018-10-19 21:48 UTC, volas commented on rules.md
> +### И еще немного об административных действиях
Чуть позже следует дописать "обязанности", до сих пор не всем игрокам очевидны.
И то обвиняют в щитспавне и заговорах, то пытаются нагружать не связной работой...

2018-10-19 23:49 UTC, EdlerN commented on rules.md
> +5. Флавор существует сугубо для описания внешности персонажа. Нет, серьезно. Не стоит писать туда историю получения воон того шрама. Даже если очень хочется. Ведь другим будет намного интереснее узна
У нас же были войны за флавор, по которым еще амби заставили свой менять когда-то. Впрочем, я не скажу чтобы в них было прям так уж много смысла. Можно и так.

2018-12-12 10:23 UTC, RichardJones1 commented on rules.md
> +3.2.1 Если у вас возникли какие-то проблемы с механикой - напишите менторам (кнопка F9) если вы считаете, что обнаружили баг - напишите Администраторам (F1), если вы уверены что нашли баг - можете на
Это скорее нужно не в правила а в гайд для новичков.

2018-12-12 10:29 UTC, RichardJones1 commented on rules.md
> +3.2.2 Написание жалоб тоже стоит отложить до окончания раунда
Мне казалось, у нас была какая то более строгая позиция по этому поводу. Может вообще объединить это с пунктом выше, прямым текстом написав что во время раунда информацию о багах/нарушениях лучше писать администрации?

2019-01-19 02:53 UTC, Belfogor commented on rules.md
> +1.1 Соблюдайте нормы русского языка - пишите грамотно.
Ты всегда меня критикуешь и ругаешь.

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Уважайте других участников сообщества. В том числе и новичков. Они, вполне вероятно, могут огорчить вас даже не желая этого. Проявите понимание.
```suggestion
      - В том числе и новичков. Они, вполне вероятно, могут огорчить вас даже не желая этого. Проявите понимание.  
```
т.к. повтор предыдущего пункта по смыслу, можно сделать подпунктом.

2019-03-05 17:51 UTC, volas commented on rules.md
> +2. Поведение, направленное на намеренное причинение вреда другим игрокам без малейших на то игровых оснований, не приветствуется вплоть до выдачи перманентной блокировки без лишних разговоров
```suggestion
2. Поведение, направленное на намеренное причинение вреда другим игрокам без малейших на то игровых оснований, не приветствуется, вплоть до выдачи перманентной блокировки без лишних разговоров
```
я сам конечно так себе корректировщик, возможно нужна запятая, возможно еще одна до "без малейших" :roll_eyes:

2019-03-05 17:51 UTC, volas commented on rules.md
> +3. Метагейминг (metagame) - использование информации, полученной неигровым путем (Из любого OOC источника), для получения каких-либо игровых преимуществ серьезно вредит игровой атмосфере и потому зап
```suggestion
3. Метагейминг (metagame) - использование во время игры информации, полученной не игровым путем (из любого OOC источника), серьезно вредит игровой атмосфере, и потому запрещен. Сюда относится игра с использованием сторонних чатов (голосовых или текстовых) для кооперации действий.
Ваш персонаж не должен мчаться спасать друга на другой стороне станции, если персонаж (а не вы) не знает об этом. Или готовится к определенному режиму игры без явных к этому IC-предпосылок.
```
Небольшие корректировки, и переформулировал вторую часть про ведьм, что бы лучше донести примеры (предложение).

Еще мне нравится из нынешних правил глоссарий, на который можно сослаться. Тут ты приводишь расшифровку метагейма, но не разъясняешь что есть OOC. Возможно стоит как на [парадайзах](https://nanotrasen.se/rules/) добавить краткий перечень в начале. Можно потом.

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Есть, однако, небольшое исключение. Если вам хочется показать кому-то из своих знакомых эту игру, при этом попутно объясняя происходящее - обратитесь к администраторам. Это вполне допустимо.
```suggestion
   - Есть, однако, небольшое исключение. Если вам хочется показать кому-то из своих знакомых эту игру, при этом попутно объясняя происходящее - обратитесь предварительно к администраторам. Это вполне допустимо, но во избежание недоразумений лучше предупредить. К тому же, администраторы могут вам помочь, даже отправить в не игровую зону станции.
```
не уверен по поводу полезности последнего предложения

2019-03-05 17:51 UTC, volas commented on rules.md
> +    - Помимо этого, стоит учитывать некоторые игровые условности касательно доступности информации. К примеру, по умолчанию, большинство информации об антагонистах считается неизвестной для экипажа.
```suggestion
    - Стоит учитывать некоторые игровые условности касательно знаний **персонажа** о мире игры. По умолчанию, большинство информации об антагонистах считается неизвестной для экипажа. Подробнее можно посмотреть в [данной статье на вики](https://wiki.taucetistation.org/Identifying_Antagonists).
```
"К примеру" подразумевает, что есть еще что-то кроме приведённого примера. А больше вроде ничего нету.

2019-03-05 17:51 UTC, volas commented on rules.md
> +2. Поведение, направленное на намеренное причинение вреда другим игрокам без малейших на то игровых оснований, не приветствуется вплоть до выдачи перманентной блокировки без лишних разговоров
Еще это всё еще пересечение по смыслу с рул 0. Я бы переместил в подпункт рул 0.

Еще не указано, при каких обстоятельствах может приниматься решение о "перме без разговоров". Уверен, Белфогор уже потирает руки.

В текущих правилах для схожего пункта было "по решению старших администраторов".

2019-03-05 17:51 UTC, volas commented on rules.md
> +4. Распространение любой информации о текущем раунде посредством любых OOC средств запрещено. Сюда попадает как игровой OOC канал, так и любые сторонние форумы/чаты. Информация и ее распространение в
```suggestion
4. Распространение информации о текущем раунде посредством OOC средств запрещено. Сюда попадает как игровой OOC канал чата, так и любые сторонние форумы/чаты и прочие средства общения. Информация и ее распространение в игре является одним их тех элементов, что делает многие раунды интересными. Внезапные предательства, обман, блеф и прочее. А потому, преждевременное ее обсуждение вне рамок раунда - может испортить интригу и впечатление от игры.  
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Если у вас возникли какие-то проблемы с механикой - напишите менторам (кнопка F9) если вы считаете, что обнаружили баг - напишите Администраторам (F1), если вы уверены что нашли баг - можете нап
```suggestion
   - Если у вас возникли какие-то проблемы с механикой - напишите менторам (кнопка F9). Если вы считаете, что обнаружили баг - напишите Администраторам (F1). Если вы уверены что нашли баг - можете написать о нем сразу на гитхаб.
Если вы считаете что кто-то делает что-то не-так, можете попробовать написать ему в LOOC (локальный OOC чат, который отображается только у администраторов и тех, кто находится в данный момент рядом с вами), либо попросить Администратора подсказать человеку, в чем он не прав.  
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Написание жалоб на форум или в дискорд так же стоит отложить до окончания раунда.
```suggestion
   - Написание жалобы по раунду на форум или в дискорд так же стоит отложить до окончания раунда.  
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +4. Пауэргейминг (powergaming, powerplay), или, перефразируя - стремление любыми способами “победить в игре” не приветствуется. Как правило, данное поведение характеризуется как “приоритизация получен
```suggestion
4. Пауэргейминг (powergaming, powerplay), или, перефразируя - стремление любыми способами “победить в игре”, не приветствуется. Как правило, данное поведение характеризуется приоритезацией получения различных игромеханических преимуществ для себя, в ущерб удовольствию, получаемому от игры другими игроками и/или созданию интересных игровых ситуаций.  
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Сюда в некоторой степени относится манчкинизм - стремление снарядить своего персонажа на все случаи жизни, не учитывая конкретной ситуации.
```suggestion
   - Сюда же относится манчкинизм - стремление снарядить своего персонажа на все случаи жизни, не учитывая конкретной ситуации.     
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Особо стоит отметить использование некоторых неочевидных и, зачастую, спорных моментов игровой механики для получения преимуществ. Такие моменты должны быть сведены к минимуму. Использование нез
```suggestion
   - Особо стоит отметить намеренное использование багов и недоработок игры для своей пользы. Лучше сообщите о них на гитхаб.
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Да, на дворе 25** год и ваш персонаж вполне может знать о событиях на земле 21-го века, но это совершенно не повод начинать орать имена известных политических деятелей того периода в радио. Или
```suggestion
   - Да, на дворе 26 век, и ваш персонаж вполне может знать о событиях на земле 21-го века, но это совершенно не повод начинать орать имена известных политических деятелей того периода в радио. Или привносить любую другую информацию из сторонних источников в игру. В особенности, если оно ну совсем не вписывается в картину космической станции на задворках далекого будущего  
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +     - Есть небольшое исключение. К примеру, обмен ссылками на какую-нибудь музыку через ПДА, в случае если вы замените название сайта на что-то более подходящее для этой вселенной (тот же wetskrells
```suggestion
     - Есть небольшое исключение. Вы можете обмениваться ссылками на какую-нибудь музыку через ПДА, в случае если вы замените название сайта на что-то более подходящее для этой вселенной (тот же wetskrells.nt). О деталях можете договориться в LOOC. Прямое использование ссылок без изменений все так же остается под запретом.  
```

Другой вариант... имхо, заставлять перебивать ссылки одних и других - не очень.

```suggestion
     - Есть небольшое исключение. Вы можете обмениваться ссылками через ПДА, если это музыка (youtube, soundcloud), наша wiki игры (обосновывая как "служебные инструкции").  
```
Еще это можно технически скорее всего решить, составить список доступных доменов для использования. :thinking:

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Политические и религиозные дебаты в ооц под запретом. Это те самые темы, которые, зачастую, приводят к конфликтам, которые никто не хочет разрешать. А как следствие - переход на личности и оскор
```suggestion
```
Пункт про атмосферу игры (IC), подпункт про OOC общение. Лучше перенести.

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Спам запрещен.
```suggestion
   - Спам запрещен.  
   - Под запретом так же политические и религиозные дебаты, так как являются слишком конфликтными темами. Оставьте это для специализированных форумов. Вы ведь пришли сюда играть в 2д-космонавтов, не так ли?  
```

Перенос, ниже есть комментарий.

В то же время, является ли это "нормами общения"? Наверно стоит первый пункт переименовать, что бы лучше подходило, но пока нет идей...

2019-03-05 17:51 UTC, volas commented on rules.md
> +   - Не стоит оскорблять других участников сообщества
```suggestion
   - Уважайте других участников сообщества.  
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +      - Под это правило подпадает эскалация спора с переходом на личности. Пишите взвешенно и аргументированно.
```suggestion
      - Под это правило подпадает эскалация спора с переходом на личности и оскорбления. Пишите взвешенно и аргументированно.  
```
(ай, всё равно это никто не соблюдает)

2019-03-05 17:51 UTC, volas commented on rules.md
> +6. Запрещено распространять личные данные другого участника сообщества без его согласия.
```suggestion
6. Запрещено распространять личные данные других участников сообщества без их на то согласия (фото, профили соц сетей).
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +7. Реклама, в особенности коммерческая, без согласования с Администрацией сервера - запрещена.
```suggestion
7. Запрещена реклама сторонних серверов без согласования с администрацией. Вы можете свободно обсуждать сторонние сервера, но предоставлять информацию о конкретном сервере можно только на форуме. Под запретом так же любая коммерческая реклама. 
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +8. Порнографический или любой другой NSFW ("Not Safe For Work" или "не безопасный для работы" - не приемлемый в приличном обществе) контент под запретом в OOC каналах.
```suggestion
8. Порнографический или любой другой NSFW ("Not Safe For Work" или "не безопасный для работы" - не приемлемый в приличном обществе) контент под запретом.
```
А то начнут в ПДА кидать...

2019-03-05 17:51 UTC, volas commented on rules.md
> +9. Игра предназначена для лиц старше 16 лет. Если ваш возраст не соответствует - немедленно закройте игру.
```suggestion
9. Игра предназначена для лиц старше 16 лет. Если ваш возраст не соответствует - немедленно покиньте игру!
```

2019-03-05 17:51 UTC, volas commented on rules.md
> +10. Запрещено использовать для игры на сервере несколько более одного аккаунта byond.
```suggestion
10. Запрещено использовать более одного аккаунта byond для игры на сервере.   
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +1. Ступиднейм - имя, нарушающее пункт 5 общих правил. Это может быть имя какой-то известной личности, имя с  добавлением туда непонятных “кличек”, либо просто что-то достаточно глупое. Рекомендуется
```suggestion
1. Используйте реалистичные имена, в случае игры за ксеноса используйте имена в соответствии с лором игры.
   - Ступиднейм - имя, нарушающее пункт правил об атмосфере игры. Это может быть имя какой-то известной личности, имя с  добавлением туда непонятных “кличек”, либо просто что-то достаточно глупое. Рекомендуется избегать подобных имен. В случае, если вам очень хочется как-то назвать своего персонажа, но у вас есть сомнения, - обратитесь к Администратору.   
```
Вернул текущую формулировку, мне она больше нравится. Убрал отсылку к конкретному номеру - это плохая идея, так как правила будут туда-сюда тасоваться, а упоминание номера мы обязательно забудем поменять (да и в целом я не раз высказывался о плохой идее нумерации правил).

Тут и ниже несколько общих правок.

2019-03-05 18:32 UTC, volas commented on rules.md
> +   - Имя известной личности с минимальными изменениями в духе замены одной буквы, перестановки местами фамилии и имени и тому подобным - все так же является ступиднеймом. Нет, нам не нужны Алексеи Ов
```suggestion
      - Имя известной личности с минимальными изменениями в духе замены одной буквы, перестановки местами фамилии и имени и тому подобным - все так же является ступиднеймом. Нет, нам не нужны Алексеи Овальные на станции.   
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +   - В случае нарушения данного правила администрация оставляет за собой право принудительно переименать вашего персонажа по своему усмотрению.
```suggestion
```

Имхо излишне. Или можно к каждому правилу такую приписку делать.

2019-03-05 18:32 UTC, volas commented on rules.md
> +2. Уважайте такие понятия как “адекватная эскалация конфликта” и “мотивация”.
```suggestion
2. Уважайте такие понятия как “адекватная эскалация конфликта” и “мотивация”.  
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +И потому, старайтесь не сводить решение любой проблемы к устранению противоборствующей стороны. Подробнее об убийствах тут [link]
```suggestion
И потому, старайтесь не сводить решение любой проблемы к устранению противоборствующей стороны. Подробнее об убийствах можете почитать [тут](https://wiki.taucetistation.org/Убийства).
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +3. Уважайте цепь командования. Помните, вы - команда станции. А главы - лидеры этой команды. Да и, в конце концов - для того чтобы послать куда подальше прямого начальника, от которого зависит ваше д
```suggestion
3. Уважайте цепь командования. Помните, вы - команда станции. А главы - лидеры этой команды. Для того, чтобы послать куда подальше прямого начальника, от которого зависит ваше дальнейшее трудоустройство - неплохо бы иметь хоть какую-то причину.
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +7. Если игра не выдала вам роль антагониста - вы не являетесь им. Ваша мама не генокрад, ваш отец не офицер отряда смерти, и вы не занимаетесь тем что между чашками кофе продаете биологическое оружие
```suggestion
7. Если игра не выдала вам роль антагониста - вы не являетесь им. Ваша мама не генокрад, ваш отец не офицер отряда смерти, и вы не занимаетесь тем, что между чашками кофе продаете биологическое оружие на сторону. А если и занимаетесь то уж точно не станете говорить об этом никому на станции, правда ведь? Это, впрочем, не запрещает вам быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и тому подобным. Однако, следует придерживаться некоторых рамок. В общем случае правило следующее - целью ваших действий не должно быть что-то что выльется в вывод из игры другого игрока. Вашей целью не должны быть предметы высокого риска и некоторые уникальные предметы, отсутствие которых может сказаться на развитии раунда. Если вас застукали - вы не должны эскалировать ситуацию. Помимо этого, хорошим тоном будет предварительно уведомить Администрацию о своих намерениях.
```
:heart:

2019-03-05 18:32 UTC, volas commented on rules.md
> +8. Отыгрыш персонажа, принадлежащего к какой-либо ксенорасе должен учитывать особенности лора данной ксенорасы.
```suggestion
8. Отыгрыш персонажа, принадлежащего к какой-либо ксенорасе, должен учитывать особенности лора данной ксенорасы. 
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +9. В процессе раунда некоторые ситуации сказываются на поведения вашего персонажа. Зачастую это связанно с той или иной формой "промывки мозгов". Пожалуйста, отыгрывайте данные изменения корректно.
тут бы примеры под "корректно" не помешали бы

2019-03-05 18:32 UTC, volas commented on rules.md
> +10. Второй слой карты (ЦК, велосити и базы антагонистов) является не-игровым пространством, за исключением некоторых случаев.
Нет определения, что есть не-игровая зона и чем отличается. В зависимости от этого определения может потребоваться корректировка пунктов ниже.

2019-03-05 18:32 UTC, volas commented on rules.md
> +3. Как от представителя высшего эшелона власти на станции, от вас ожидается куда более уважительное отношение к иерархии приказов и прочему. В конце концов, это тот инструмент который позволит вам де
```suggestion
3. Как от представителя высшего эшелона власти на станции, от вас ожидается куда более уважительное отношение к иерархии приказов и прочему. В конце концов, это тот инструмент, который позволит вам держать ситуацию под контролем. Или скатить в неконтролируемый хаос, если вы начнете им пренебрегать. 
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +4. Как от главы от вас ожидается то, что вы будете следовать протоколам и инструкциям Корпорации, которая назначила вас на этот пост и, вероятно, платит вам немалые деньги за работу.
```suggestion
4. Как от главы, от вас ожидается то, что вы будете следовать протоколам и инструкциям Корпорации, которая назначила вас на этот пост и, вероятно, платит вам немалые деньги за работу. Подробнее ознакомиться со стационной бюрократией можно [тут](https://wiki.taucetistation.org/Категория:Бюрократия и процедуры).
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +5. Учитывайте, что ваши решения могут иметь далеко идущие последствия. При этом, ответственность за отданный приказ несете именно вы, и лишь в меньшей степени тот кто его исполнит. Поэтому, стоит быт
```suggestion
5. Учитывайте, что ваши решения могут иметь далеко идущие последствия. При этом, ответственность за отданный приказ несете именно вы, и лишь в меньшей степени тот, кто его исполнит. Потому будьте осмотрительны с формулировками. 
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +1. Офицер службы безопасности - дисциплинированный боец, который прошел тщательный отбор. Они являются первым и последним рубежом защиты станции, а главным образом является той силой, которая призван
```suggestion
1. Офицер службы безопасности - дисциплинированный боец, который прошел тщательный отбор. Они являются первым и последним рубежом защиты станции. Силой, которая призвана поддерживать внутренний порядок на бору станции и способствовать сохранению корпоративных интересов, в числе прочего служить их законным представителям, то бишь главам.   
```
Слишком сложное предложение. Я попытался подкорректировать, но не совсем понял мысль про "в лице служению"

2019-03-05 18:32 UTC, volas commented on rules.md
> +   -   Соблюдайте иерархию приказов [link]. Постарайтесь максимально ответственно отнестись к выполнению поставленных вам задач.
```suggestion
   - Соблюдайте [иерархию приказов](https://wiki.taucetistation.org/Standard_Operating_Procedure#Иерархия приказов). Постарайтесь максимально ответственно отнестись к выполнению поставленных вам задач.  
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +   - Соблюдайте протоколы космического закона [link] и внутренний порядок действий, когда это возможно.
```suggestion
   - Соблюдайте [протоколы космического закона](https://wiki.taucetistation.org/Space_Law) и внутренний порядок действий, когда это возможно.  
```

2019-03-05 18:32 UTC, volas commented on rules.md
> +0.4 Ответственность за действия совершенные при выполнении законов синтетом в большей степени несет тот, кто установил эти законы. Но трактовка остается на ваше усмотрение. Используйте это разумно и
```suggestion
0.4 Ответственность за действия, совершенные при выполнении законов, в большей степени несет тот, кто установил эти законы. Но трактовка остается на ваше усмотрение. Используйте это разумно и постарайтесь чтобы это не стало причиной гибели станции.
```

2019-03-05 18:34 UTC, volas commented on rules.md
> +0.5.1 В исключительных случаях Администрация оставляет за собой право закрывать доступ к позициям антагонистов без дополнительных пояснений ссылаясь на это правило и, если ситуация того требует, обес
```suggestion
```
Слишком вода и не понятно... и в любом случае, администрация всегда оставляет за собой правило закрывать доступ ссылаясь на любое из правил. Либо нужно лучше расписать мысль.

2019-03-05 18:37 UTC, volas commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
Тут я хотел бы уточнить, какие знания, и наказываются ли за эти знания другие игроки (правило о метагейме?).

Мне нравится новая формулировка метагейма, но тут вдруг это.

2019-03-05 18:41 UTC, volas commented on rules.md
> +5. Администрация оставляет за собой право переносить баны с других серверов.
Пока лишне. Если сервера еще будут, то скорее всего с общей банбазой.
Либо переформулировать под перенос банов с форума/дискорда (хотя тоже может лишнее)

2019-03-05 19:28 UTC, EdlerN commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
Надо капельку переформулировать. Внутриигровые знания, т.е. - знания проф.

2019-03-05 19:30 UTC, volas commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
Просто выше нигде эти знания проф не упоминаются

2019-03-05 19:32 UTC, EdlerN commented on rules.md
> +8. Порнографический или любой другой NSFW ("Not Safe For Work" или "не безопасный для работы" - не приемлемый в приличном обществе) контент под запретом в OOC каналах.
Там основная проблема в том что у нас сама игра сплошной нсфв контент....

2019-03-05 19:37 UTC, volas commented on rules.md
> +8. Порнографический или любой другой NSFW ("Not Safe For Work" или "не безопасный для работы" - не приемлемый в приличном обществе) контент под запретом в OOC каналах.
Хотя да, та самая проблема Вуди.

2019-03-11 18:48 UTC, Belfogor commented on rules.md
> +8. Порнографический или любой другой NSFW ("Not Safe For Work" или "не безопасный для работы" - не приемлемый в приличном обществе) контент под запретом в OOC каналах.
Да. надо бы начать как-то этот ФСФВ контект и прочий брейнрот выпиливать. А то у нас много брейрота в самом механе. Ехх.

2019-03-11 18:50 UTC, Belfogor commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
>Большинство антагонистов может

Тут наверное нужно более точно указать кто и что, но это кажется не для самих правил. Возможно потребуется отдельная статья на вики, где стоило бы четко изложить такие аспекты. Поскольку формулировка вроде правильная, но очень туманна. Я то ориентируюсь, но как быть условному новичку, посчитавшему что культист таки может, он же большинство или нет?

2019-03-11 18:52 UTC, Belfogor commented on rules.md
> +5. Администрация оставляет за собой право переносить баны с других серверов.
Пусть будет. А если таки на ТауКеке когда-нибудь появится второй сервер. И таки не если, а когда. Время от времени у нас поднимаются сервера с другими билдами, в качестве развлекаловки.

2019-03-11 18:55 UTC, volas commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
>Я то ориентируюсь

я бы поспорил :peka:

2019-03-11 18:57 UTC, Belfogor commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
Шутник. Но чувствую что у нас даже внутри самого педального коллектива не будет консенсуса на этот счет.

2019-03-28 08:58 UTC, EdlerN commented on rules.md
> +2. Большинство антагонистов может использовать все доступные знания и умения.
Обновил

2019-03-29 19:21 UTC, Belfogor commented
В релиз уже давайте.

2019-03-30 06:18 UTC, volas commented on rules.md
> +10. Воздержитесь от использования не-игровых территорий в процессе игры. Как правило это некие технические зоны, проникновение в которые связано с использованием недоработок игровой механики, etc. По
Воздержаться от использования велосити сложно, если зашел после раунда. 
И всё еще не понятно к чему правило. Может взять из текущих правил формулировку?

2019-03-30 09:52 UTC, merged