Исправления стиля, мелкие исправления ошибок, оформления и прочее
TauCetiStation/Rules pull request #34
Opened 2019-11-08 11:19 UTC by skvazarb

Попытался уменьшить несколько заметных проблем в текущей редакции правил. Общая проблема - некоторые пункты или части правил не выдержаны в общем письменном стиле. Происходит переход с практически официально-делового стиля на рассуждения, необходимость наличия которых под вопросом, или шутки очень близко к разговорному стилю. Среди намерений было попытаться немного уменьшить объем, но надо сказать, что почти безуспешно.

Суть правил нигде не менялась, только формулировки. Еще из общего — заменил все случаи использования дефиса вместо тире. Потому что использовать дефисы вместо тире - это очень плохо.

Правила для отдельных ролей сейчас почти не трогал, потому что вообще в вики-стиле, а не в стиле правил написано, не знаю что с этим можно сделать.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -     - Слэнг борд, лурка и иже с ними лучше оставить там же.
Тут какой-то старославянский был, а мы здесь деградировать собрались

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -   - Если у вас возникли какие-то проблемы с механикой - напишите менторам (кнопка F9). Если вы считаете, что обнаружили баг - напишите Администраторам (F1). Если вы уверены что нашли баг - можете на
Полностью лишняя информация в правилах, может быть добавлена в сообщении при входе в игру, например.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -7. Запрещена реклама сторонних серверов без согласования с администрацией. Вы можете свободно обсуждать сторонние сервера, но предоставлять информацию о конкретном сервере можно только на форуме. Люб
Непонятно как можно одновременно "свободно обсуждать сторонние сервера" и при этом не "предоставлять информацию о конкретном сервере". Формулировки о рекламе достаточно, чтобы правило было понятным.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -0.1 Каким бы персонажем вы бы не решили играть - помните, если ваше удовольствие будет достигаться ценой раздражения окружающих - это не хорошо. А потому - старайтесь держать себя в руках. Конфликты
О конфликтах персонажей дальше и так идет отдельный пункт, одного раза достаточно.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> +1. Используйте реалистичные имена, в случае игры за инопланетные расы используйте имена в соответствии с лором игры.
Обозначение "ксеносы" звучит слишком сленговым и почти оскорбительным. Предлагаю для правил использовать литературную версию.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -5. Флавор существует сугубо для описания внешности персонажа. Нет, серьезно. Не стоит писать туда историю получения воон того шрама. Или описывать характер персонажа. Даже если очень хочется. Ведь др
Формулировка из первого предложения достаточно исчерпывающая.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -7. Если игра не выдала вам роль антагониста - вы не являетесь им. Ваша мама не генокрад, ваш отец не офицер отряда смерти, и вы не занимаетесь тем, что между чашками кофе продаете биологическое оружи
Удалил шутейки, так как они плохо вписываются в общий стиль.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> +4. Как от главы, от вас ожидается то, что вы будете следовать протоколам и инструкциям Корпорации, которая назначила вас на этот пост и, вероятно, платит вам немалые деньги за работу. Подробнее ознак
На самом деле название раздела на вики плохо отражает суть, в этом разделе нет почти ничего общего с общепринятыми значениями слова "бюрократия", поэтому лучше не вводить никого в заблуждение лишний раз.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -0.3 Офицеры имеют значительное влияние на происходящее в раунде,  выше, чем у многих других играющих, а соответственно, и степень их ответственности на порядок выше. Нередко их влияние сопоставимо с
Традиционное напоминание, что "на порядок" это в ~10 раз. Не наш случай.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> +2. На антагониста в меньшей степени распространяются правила, касающиеся внутриигровых умений персонажа.
Заменил двусмысленное определение "знаний", под которым можно подразумевать как и метанавыки, так и метазнания на более понятное "умений" про работку.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> +   - Цель принятия Административных мер - разрешение конфликта и улучшение качества игры.
Лексическая ошибка

2019-11-08 11:28 UTC, skvazarb commented on index.md
> +   - Если вас официально попросили что-то прекратить, или наоборот сделать — это имеет силу правила.
Дальше есть отдельный пункт про споры в приватных сообщений, одного раза достаточно.

2019-11-08 11:28 UTC, skvazarb commented on index.md
> -   - Вмешательство, однако, не должно нарушать игровой логики. Свинья с неба в храме это, конечно, хорошо и весело, но нужно знать чувство меры. К примеру, вмешиваться в идущий конфликт с целью помоч
Еще шутка, которая плохо вписывается в общий стиль.

2019-11-08 11:36 UTC, volas commented
Боже мой да, герой которого мы ждали целый год!

2019-11-08 18:08 UTC, igigin commented on index.md
> +     - Сленг борд, лурка и т.д. лучше оставить там же.
> и т.д.

Лучше `и т.п.`

2019-11-08 18:08 UTC, igigin commented on index.md
> +0.1 Каким бы персонажем вы бы не решили играть — помните, ваше удовольствие не должно достигаться достигаться ценой раздражения окружающих.
достигаться достигаться

2019-11-08 18:08 UTC, igigin commented on index.md
> +   - Если вы считаете что кто-то делает что-то не-так, можете попробовать написать ему в LOOC (локальный OOC чат, который отображается только у администраторов и тех, кто находится в данный момент ря
вы считаете, что кто-то делает

2019-11-08 18:08 UTC, igigin commented on index.md
> +   - Запрещенно использование каких-либо видов стороннего программного обеспечения: скрипты, макросы и читы.
- Запрещено использование...

2019-11-08 18:08 UTC, igigin commented on index.md
> +   - Цель принятия Административных мер - разрешение конфликта и улучшение качества игры.
— забыл

2019-11-08 18:08 UTC, igigin commented on index.md
> +5. Решение Администратора в раунде окончательно, не нужно пытаться оспорить его в игре — это ни к чему хорошему не приведёт. Если вы не согласны с администратором по каким-либо вопросам - обратитесь
И тут тире
и выянсить

2019-11-10 18:57 UTC, volas requested changes

2019-11-10 18:57 UTC, volas commented on index.md
> +   - Написание жалобы по событиям раунда на форум или в дискорд стоит отложить до окончания раунда.
```suggestion
   - Написание жалобы по событиям раунда на форум или обсуждения в дискорде стоит отложить до окончания раунда.  
```

2019-11-10 18:57 UTC, volas commented on index.md
> +   - Прямые трансляция раундов без предварительного согласования запрещены. Для согласования трансляции обратитесь к администрации.
тут кстати задумался, со стороны администрации про эти согласования нигде не порписано, нужно обновить кодекс

2019-11-10 18:57 UTC, volas commented on index.md
> +7. Запрещена реклама сторонних серверов без согласования с администрацией. Любая коммерческая реклама под запретом!
Это многострадальное правило, тут нужно упомянуть что:
* запрещена реклама серверов (навязчивый спам и тд тп)
* пояснение что просто обсуждать их легально
* а еще под запретом коммерческий спам. Хотя я не помню, что бы у нас кто-то так развлекался, но нельзя исключать вариантов что если кто-то захочет что-то рекламить на сервере, это будет обязательно другой сервер сс13 и попадёт под первую часть.

Дак вот, второй момент пропал. Я думаю, он важен, а то опять кто-то завахтерится.

2019-11-10 18:57 UTC, volas commented on index.md
> +5. Флавор существует сугубо для описания внешности персонажа.
```suggestion
5. Флавор существует сугубо для описания внешности персонажа. Не нужно описывать в флаворе "впечатления" о персонаже, или его историю.
```
Я бы оставил небольшое пояснение, всё же. Для многих этот момент не очевиден. Как думаешь?

2019-11-11 03:37 UTC, skvazarb commented
Добавил предложенное отдельным комитом, с тем исключением, что переделал дополнения в качестве противопоставления к изначальным тезисам. Поскольку эти дополнения на самом деле прямым образом следуют из самих тезисов, то когда оно сформулировано в виде неполного противопоставления, выглядит как будто мы уточняем тезис, а не пишем по второму разу одно и то же.

2019-11-11 03:42 UTC, volas approved these changes

2019-11-11 10:34 UTC, EdlerN approved these changes

2019-11-11 13:08 UTC, JacobTaken commented on index.md
> +2. Серьезные конфликты должны развиваться только постепенно и только при условии сохранении игровой мотивации оппонентов. Поэтому старайтесь не сводить решение любой проблемы к устранению противоборс
>Серьезные конфликты должны развиваться только постепенно и только при условии сохранении игровой мотивации оппонентов. Поэтому старайтесь не сводить решение любой проблемы к устранению противоборствующей стороны.

Предыдущая формулировка правила была универсальной, так как не вводила разделение конфликтов по степени серьёзности. ИМХО, вводить такое разделение в правила лишнее, так как нигде нет критериев для такого деления, а вводить их — захламлять правила. В таком виде правило оставляет слишком большой простор для любителей демагогии уровня "Я считаю, что у меня конфликт не серьёзный, а у вас правило про серьёзные..." Кроме того, в данной формулировке потерялся смысл понятия "адекватная эскалация конфликта", отчего причинно-следственная связь первого и второго предложений потерялась: во втором предложении говорится про решение "любой проблемы" убийством, а в первом про "серьёзные конфликты" и ничего про адекватное развитие конфликта. Если всё же закрыть глаза на нарушение причинно-следственной связи предложений в правиле, то получается, что правило свелось лишь к ограничению на убийства, тогда как в своей изначальной формулировке оно подразумевало и менее банальные способы неадекватного развития конфликта.

Я бы предложил следующую формулировку для первого предложения правила: "Конфликты персонажей должны основываться на их внутриигровой мотивации в раунде, развиваться постепенно и соразмерно этой мотивации". 

Какое твоё мнение?

2019-11-11 13:14 UTC, JacobTaken commented on index.md
> +   - Если вас официально попросили что-то прекратить, или наоборот сделать — это имеет силу правила.
Следующий подпункт про суточный бан был напрямую связан с подпунктом про "Крайне не рекомендуется пытаться оспорить решение Администратора в приватных сообщениях". Сейчас же он после переноса этого подпункта стал связан с подпунктом про "Если вас официально попросили что-то прекратить, или наоборот сделать — это имеет силу правила." Из-за перестановки пункта изменился смысл правила про суточный бан.

2019-11-11 13:45 UTC, skvazarb commented on index.md
> +   - Если вас официально попросили что-то прекратить, или наоборот сделать — это имеет силу правила.
Если читать этот текст как он написан, то угроза суточного бана относится к правилу в целом, которое звучит как "Слушайте, то что вам говорит Администратор" и не относится к конкретному пункту. Тем более вряд ли кто-то собирается выдавать суточные баны вместо мутов за споры в приватных сообщениях.

2019-11-11 13:57 UTC, skvazarb commented on index.md
> +2. Серьезные конфликты должны развиваться только постепенно и только при условии сохранении игровой мотивации оппонентов. Поэтому старайтесь не сводить решение любой проблемы к устранению противоборс
Конфликты - основная движущая сила раундов. Сами по себе они не только запрещены, но в частых случаях даже приветствуются. Это настолько важно, что я даже добавил дальше отдельный, поясняющий что конфликты на пустом месте ничуть не запрещены `Вы можете спровоцировать конфликт с другим игроком в пределах разумного, но основную ответственность за последствия будет нести зачинщик.` Поскольку мелкие конфликты относятся к игровым ситуациям и не рассматриваются ни правилами, ни администрацией. Поэтому добавления к запрету формулировки "серьезные" кажется мне совершенно принципиальным. Разумеется эта формулировка включает в себя субъективную оценку, как и примерно 95% остального содержимого правил , но она точно ничуть не более субъективная чем, например, “адекватная эскалация конфликта”, которая больше походила на рандомный набор слов. Мне нравится в предложении добавления понятия "соразмерно" и лексически "внутриигровой" здесь подходит больше чем игровой. А по поводу серьезности нам придется дождаться третьих мнений. Возможность устроить персоналу между собой конфликт, который будет развиваться строго постепенно и при желании обоих участников вплоть до каких-нибудь тяжелых последствий представляется мне полностью соответствующим духу правил и содержим обыкновенного раунда.

2019-11-11 14:28 UTC, skvazarb commented on index.md
> +2. Серьезные конфликты должны развиваться только постепенно и только при условии сохранении игровой мотивации оппонентов. Поэтому старайтесь не сводить решение любой проблемы к устранению противоборс
Можно без особо ущерба дописать так:
```Серьезные конфликты (особенно с применением насилия) <...>```
Все равно конфликты без насилия нас почти никогда не интересуют с точки зрения правил. А любой конфликт, где люди пошли убивать друг друга или хотя бы бить морду невозможно посчитать несерьезным. Так и мы достаточные пояснения дадим и игроков не сильно вахтерим. Но я все еще сомневаюсь что это вообще нужно.

2019-11-11 16:33 UTC, volas commented on index.md
> +2. Серьезные конфликты должны развиваться только постепенно и только при условии сохранении игровой мотивации оппонентов. Поэтому старайтесь не сводить решение любой проблемы к устранению противоборс
@JacobTaken я пока мержу в черновую версию, а не в чистовую что у нас на сайте. Если есть еще замечания к этому пункту - можешь создать ПР в draft (если есть желание но не знаком с гитом, напиши, я объясню как).

2019-11-11 16:34 UTC, merged

2019-11-12 11:31 UTC, JacobTaken commented on index.md
> +2. Серьезные конфликты должны развиваться только постепенно и только при условии сохранении игровой мотивации оппонентов. Поэтому старайтесь не сводить решение любой проблемы к устранению противоборс
После пояснений Сквазаря и небольшого дополнения формулировки правила у меня замечаний больше нет. Благодарю Сквазаря за проделанную работу, в том числе по фидбеку.