Различные мелкие правки
TauCetiStation/Rules pull request #66
Opened 2020-09-25 16:58 UTC by skvazarb

По большей части удалены всякие пробелы, исправлены опечатки и все такое. Надеюсь это последний ПР с техническими правками(нет). Вдобавок попробовал без потери изначального смысла поправить несколько формулировок, которые, как мне показалось, часто воспринимают или слишком широко или вообще не так как задумывалось. Неочевидные нюансы подробнее рассмотрю в ревью.

2020-09-25 17:15 UTC, skvazarb22 commented on index.md
> +   - Написание жалобы (кроме жалоб в ahelp) по событиям раунда стоит отложить до окончания раунда.
Возможно я слишком сильно загоняюсь, но если читать прям дословно, то здесь как будто было запрещено писать жалобы в том числе в ахелп во время раунда. Не знаю понял ли кто-то этот пункт так дословно, но лучше перестраховаться, может и не очень изящно.

2020-09-25 17:15 UTC, skvazarb commented on index.md
> +1. Если в ваши задачи не входит физическое уничтожение всего экипажа, то вам по прежнему запрещается убивать других игроков без всякой причины. Действуйте в соразмерности со своими целями.
Здесь изначально собирались написать понятное разрешение нюкерам убивать кого угодно, но в процессе добавили мягкий намек для всех остальных антагонистов, что им все еще запрещено так делать. Как показала практика, формулировка оказалась довольно неудачной и понималась неоднозначным образом. Заменил на более конкретную, где прямым текстом написано что именно запрещено.

2020-09-25 17:15 UTC, skvazarb commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
А здесь уже прям сложно. Фактически у нас есть антагонисты, у которых нет никаких ролевых ограничений для убийства экипажа и даже могут быть какие-то причины. В целом мне кажется гораздо более последовательным не размазывать эту проблему по всем правилам, а рассматривать "лишние" убийства как гриф или метагейм в зависимости от ситуации, лора, отдельных договоренностей, а в самих правилах антагониста в качестве пояснения перечислить возможные поводы, хотя бы один из которых обязательно должен присутствовать. Т.е., например, малф, выпускающий форон в начале раунда может (и должен будет) быть забанен за метагейм, что гораздо логичнее, чем возможное использование правила для антагонистов. Обратите внимание, формулировка с достаточной ("разрешено") сменилась на необходимую ("должны быть"), но не достаточную. Если читать формулировку внимательно, то тут это ясно передано, но поскольку так никто не делает, то я согласен, что предлагаемый вариант может не идеально доносить эту мысль. Приветствуются предложения по улучшению, я пока не придумал не нелепого варианта с нужными уточнениями.

2020-11-09 07:33 UTC, skvazarb commented
Не хочется никого торопить, но прошло уже больше полутора месяцев и я осторожно напоминаю о существовании этого ПР-а.

2022-07-15 15:06 UTC, volas commented
Пробелы ничего не делают в html и лишь раздувают дифф, не считаю критичным и может даже вредным. Кавычки - нужно делать стайл гайд для них или тест. Есть хорошие правки, но они в куче с остальным багажом. Кто нибудь может вытащить и открыть свой ПР.

2022-07-24 06:48 UTC, skvazarb commented
> Кавычки - нужно делать стайл гайд для них или тест. 

На мой взгляд, учитывая что правила обновляются раз в несколько лет, это немного перебор, но это действительно полезно, поэтому добавил минималистичный вариант в https://github.com/TauCetiStation/Rules/pull/76

> Пробелы ничего не делают в html и лишь раздувают дифф, не считаю критичным и может даже вредным

Я согласен что пробелы ничего не делают,  но не понял откуда взялся вывод что их удаление это плохо. Как раз пытаюсь привести все правила к единому виду, чтобы в будущем таких проблем не возникало.

2022-09-02 19:23 UTC, volas requested changes
Я уж думал, ты не будешь заинтересован, и не придется всё это кучей обсуждать и воевать с диффом и не атомарностью или спорить из-за ненавистных мне ёлочек (серьезно, кто их вообще использует, мы в 2022 году, глобализация и всё такое) и дефисов.

Ну ладно. Не знаю только, как это потом мержить, оно будет конфликтовать со всеми остальными.

2022-09-02 19:23 UTC, volas commented on index.md
> +   - Написание жалобы (кроме жалоб в ahelp) по событиям раунда стоит отложить до окончания раунда.
излишнее уточнение

2022-09-02 19:23 UTC, volas commented on index.md
> +    - Администратор имеет право изменять статус зон на первом слое на свое усмотрение.
```suggestion
    - Администратор имеет право изменять статус не-игровых зон по своему усмотрению.
```

лучше убрать указание на номер вовсе

2022-09-02 19:23 UTC, volas commented on index.md
> +1. Если в ваши задачи не входит физическое уничтожение всего экипажа, то вам по прежнему запрещается убивать других игроков без всякой причины. Действуйте в соразмерности со своими целями.
Вернусь сюда позже...

2022-09-02 19:23 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
у нас лор шредингера и туда кто что угодно может лить, лучше не упоминать

2022-09-02 19:23 UTC, volas commented on index.md
> +1. Не стоит пренебрегать своей ролью, если уж она вам выпала. В конце концов, это игра. И многие приходят сюда именно за этим. Расследования, интриги, предательства, катастрофы и многое другое. Это т
```suggestion
1. Не стоит пренебрегать своей ролью, если она вам выпала. В конце концов, это игра. И многие приходят сюда именно за этим. Расследования, интриги, предательства, катастрофы и многое другое. Это то, что придает раунду движение.
```
инжект в тематику пр-а. хотя всё равно будет конфликтовать с другими, посмотрим

2022-09-02 19:54 UTC, skvazar commented on index.md
> +   - Написание жалобы (кроме жалоб в ahelp) по событиям раунда стоит отложить до окончания раунда.
Ок, хотя как уже говорил, если читать это строго как написано, то фактически правило запрещает жаловаться в ахелп на текущий раунд.

2022-09-02 19:59 UTC, skvazarb commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
Не, так не пойдет. Вот ключевой пункт из наших правил, например
 
 > Отыгрывайте реалистичных и естественных персонажей в соответствии с лором игры, профессией, расой, игровым режимом
 
 Я подробно описывал почему упомянуть лор важно https://github.com/TauCetiStation/Rules/pull/66#discussion_r495125488. У нас могут быть режимы, где антагонисты убивают людей не только из-за целей, логично что надо как-то включить эти случаи в правила и ссылка на лор подходит для этого лучше всего. Тем более в последней версии добавлено уточнение, что это минимальное требование, а не разрешение.

2022-09-02 20:01 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
> У нас могут быть режимы, где антагонисты убивают людей не только из-за целей

например?

2022-09-02 20:05 UTC, skvazarb commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
Самый очевидный пример - генокрады.  Культ в какой-то степени.

2022-09-02 20:26 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
генокрад как раз из-за целей, если больше нужного - то он или грифонит, или стал абоминацией и/или это обусловлено обстоятельствами раунда.

Культ - так же, или цели, или станция начинает им противостоять, культ начинает защищаться и противостоять станции, развитие конфликта

> Вот ключевой пункт из наших правил

В одном случае упор на лор в невинных вопросах отыгрыша, в другом упор на лор в вопросах убивать. Второй вопрос потяжелее для этой опоры, мне кажется.

Но я к этому вопросу еще вернусь, пока не переварил весь блок изменений.

2022-09-02 20:43 UTC, skvazarb commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
Само изменение задумывалось как стилистическое и я продолжаю так считать. Попробую еще раз объяснить идею развернуто.
Что написано в текущих правилах?

> Если в ваши задачи не входит физическое уничтожение всего экипажа, то подобное поведение находится под запретом. Действуйте в соразмерности со своими целями.

Здесь акцент делается именно на уничтожение ВСЕГО экипажа, т.е. уничтожение экипажа целиком, беспорядочные убийства, как в нюку короче, само правило и писалось под нюку https://github.com/TauCetiStation/Rules/pull/32. Но на практике оказалось, что и игроки и админы регулярно понимали это правило таким образом, что убивать кого-то можно только прям ради цели, иначе бан. Сами правила для антагонистов никогда напрямую не запрещали антагонистам убивать отдельных людей, только никак не объясняли почему это может происходить за исключением очевидного случая с целями, который уточняется отдельным пунктом. Поэтому и я убрал эту неоднозначность путем явного перечисления возможных причин, пусть и в обобщенном виде. Для левых убийств по прежнему остаются те же правила о грифе и повергейме, ровно как и до этого.

> В одном случае упор на лор в невинных вопросах отыгрыша, в другом упор на лор в вопросах убивать. Второй вопрос потяжелее для этой опоры, мне кажется.

Это же не существующие сами по себе правила. Правило о грифе запрещает убивать без причин, а требования к реалистичным персонажам, в том числе с точки зрения лора, определяют какие причины могут считаться подходящими.

2022-09-02 21:09 UTC, skvazarb commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
Аргументы про гриф от генокрадов и культ очень странные, но я не вижу смысла подробно это обсуждать, потому что считаю что в сути правил ничего не меняется. Но для референса оставлю относительно недавнее завершенное обсуждение этого вопроса на форуме (https://forum.taucetistation.org/t/diskashn-ogranicheniya-po-sozhrannym-u-genokrada/22947) и комментарии некого `volas` по поводу убийств генокрадом, который как и я считает убийства для пропитания достаточной игровой причиной.

> Это касается отсутствия ограничения на количество жертв генокрада - на данный момент он может съесть всю станцию и не подавиться, и это сложно оценивать со стороны администрации и правил. Вроде как, и не по правилам выпиливать станцию, но в то же время у генокрада есть ic-цель на это - насыщение.

(https://github.com/TauCetiStation/TauCetiClassic/issues/8339#issue-1070081648)

> И со стороны администрации в случае реализации больше не будет разночтений. Убиваешь для пропитания (пока можешь) - в рамках правил. В остальном можно будет [применять первое правило антагониста ](https://rules.taucetistation.org/#%D0%B0%D0%BD%D1%82%D0%B0%D0%B3%D0%BE%D0%BD%D0%B8%D1%81%D1%82%D1%8B).).

(https://github.com/TauCetiStation/TauCetiClassic/issues/8339#issuecomment-985096837)

2022-09-02 21:33 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственым выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
С генокрадами всё просто, там кап. Убивают до капа и не едят - гриф, Убивают и едят - всё ок. Убивают после капа и не едят - всё ок, оно уже не генокрад и деваться некуда.

По остальному, как писал, потом вернусь к этому с более свежей головой и может что-то более внятное смогу написать.

2022-12-19 22:41 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственным выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
```suggestion
   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственным выполнением целей антагониста или сложившимися обстоятельствами.
```

Я всё же считаю это спорным функциональным изменением среди кучи других "ок" стилистических правок. Что бы не держать дальше - лучше вынести в отдельный ПР, если еще требуется.

Я считаю, что лор у нас слабо контролируется администрацией, и там легко могут быть (и легко могут быть добавлены в дальнейшем и без серьезных обсуждений) странные вещи. Слишком зыбко, что бы опираться на него в правилах.

2022-12-19 22:44 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственным выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
Почему у меня нету прав на редактирование пр-а...

2022-12-19 22:48 UTC, merged

2022-12-19 22:59 UTC, volas commented
d036b2e6d58c6f7597fd90552627296fee919bc8

2022-12-20 02:35 UTC, skvazarb commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственным выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
Проблема в том, при удалении упоминания лора эта версия правок теряет согласованность. Прошлая версия читалась как достаточное условие, поэтому его выполнение можно было не считать строго необходимым. Новая же версия стала НЕОБХОДИМЫМ условием, но в такой узкой формулировке с целями она сильно ограничивает антагонистов и позволяет душить их на пустом месте. Естественно продолжать дальше это обсуждение в новом пре я уже не готов, потому что этот процесс и так растянулся на годы.

2022-12-20 05:18 UTC, volas commented on index.md
> +   - Убийства и прочие способы вывести других игроков из игры как минимум должны быть оправданы непосредственным выполнением целей антагониста, лором игры или сложившимися обстоятельствами.
имхо ок, "сложившиеся обстоятельства" ака ic-предпосылки довольно гибкое объяснение.

> растянулся на годы

ну, да, сменилось 5 или больше хедминов а мы до сих пор тут только вдвоём...