Малф и "эндшпиль" раунда
TauCetiStation/Rules pull request #69
Opened 2021-08-19 19:25 UTC by atik1n

Надо бы добавить в правила и про малфа, раз уж уже есть про нюку.
Это первая попытка, предлагайте правки, ибо я почти уверен, что она кривая.

2021-08-19 19:32 UTC, Haggerd reviewed
Что подразумевается под ОМП? Выпуск синги, разегрмоёбство, форонные ванны, тотальный выпил боргами?

2021-08-19 19:33 UTC, atik1n commented
Всё из этого. В дельта код или в случае крестового похода на ИИ, последний может выпустить сингу/теслу, ибо раунд уже почти окончен. Так как урона раунду нет, он может попытаться воспользоваться "оружием последнего шанса", а именно ОМП.

2021-08-19 19:34 UTC, Haggerd commented
А что для тебя, собственно, урон раунду?

2021-08-19 19:36 UTC, atik1n commented
Если ИИ выпустит сингу в начале раунда или из стелса - он завершит раунд досрочно и тем самым сорвёт всё, что можно.
Если уже дельта код и весь персонал идёт штурмовать ядро, то ОМП особо не помешает, ведь раунд и так уже почти завершён.

2021-08-19 19:37 UTC, Haggerd commented
У нас конец раунда определяется голосованием (Или доступом к консоли, для особо наглых), а не победой/проигрышем роли.

2021-08-19 19:41 UTC, atik1n commented
Тут шутка в том, что как бы ИИ не действовал для своей защиты (даже без масс-грифа), он повредит станцию настолько, что шаттл будет вызван почти гарантированно.
Либо выведет из игры достаточно сотрудников станции.

Просто иначе надо либо менять тут, либо менять в кодексе пометку. Нужна синхронизированность правил и кодекса.

2022-07-15 14:28 UTC, volas requested changes

2022-07-15 14:28 UTC, volas commented on index.md
> +   - ИИ в режиме "Сбойный ИИ", в случае раскрытия намерений из-за запуска самоуничтожения станции или в процессе раунда, позволяется применять оружие массового поражения, если раунд уже близится к ко
расплывчатая граница "эндшпиля" так и не была исправлена, кто нибудь может попробовать подхватить и переформулировать.
Может быть, это должно быть более выражено в коде режима.

2024-03-29 23:37 UTC, closed without merging