Правки касательно антагонистов
TauCetiStation/Rules pull request #71
Opened 2022-02-17 11:14 UTC by Lexakr

1. Прежде всего переместил и дополнил находившийся внизу первый по важности пункт:

`Помните, что цель Антагониста — разнообразить раунд чем-то веселым, захватывающим и опасным в разумных пределах. Постарайтесь приложить усилия, чтобы сделать раунд более интересным, а не просто выполнить свои цели и продолжить играть как обычно. Не пренебрегайте своей ролью, если она вам выпала.`

2. Разрешение нюкерам выпускать форон/сингу/убивать все живое
3. Уточнил пункт про умения персонажа (масс-роли и другие, просто все перечислены, если что-то забыл дополним)
4. В пункт про командных антагов добавил правила и для одиночных ролей (они и так подразумеваются, но администраторы согласятся, что игроки бывает обращаются в АХ с жалобой, что их убил тритор, когда он тоже тритор и тд)
5. Новый пункт про кемперство. Повод для дискуссии, но по-моему мнению вырезать только ступивших на станцию игроков - хрень. Сюда еще можно дописать будет кмперство ОБРовцев у их шаттла.
6. Какие-то общие правки читаемости

- [ ] Обсудить хиджак. Игроки могут или не могут уничтожать массовые катастрофы, чтобы спровоцировать вызов шаттла, вот это вот все. В моем видении могут.

2022-02-17 11:15 UTC, AndroBetel commented
О можно будет мочить мирноролей со стороны админства.

2022-02-17 11:27 UTC, Sirsolar12 commented
То есть, исходя, из первого пункта — любое мирное и максимально скрытное выполнение целей ролью — теперь нарушение правил? Правильно понял?

2022-02-17 11:42 UTC, Lexakr commented
> То есть, исходя, из первого пункта — любое мирное и максимально скрытное выполнение целей ролью — теперь нарушение правил? Правильно понял?

В предложении фигурирует слово _постарайтесь_. Суть все еще прежняя, не игнорировать роль, если она тебе выпала

2022-02-17 12:02 UTC, Dominig12 commented
Наверное проблема скрытных ролей не в том, что они скрытные, а потому что СБ даже не замечает того, что что то украли, а если и замечают не умеют искать по уликам. Как вариант лучше не менять правило а механом оставлять больше улик

2022-02-17 18:12 UTC, volas commented on index.md
> +   - Даже если вы не уверены в своих силах, лучше попробовать сделать хоть что-то.
Мне не очень нравится формулировка, слишком расплывчато и свободно. Понимание о "сделать интересным" у людей может быть разным, а потом будет "а так в правилах написано!".

Старый вариант, просто закрепляющий "не игнорируй роль", по мне был достаточным. Может только переформулировать стоило бы.

2022-02-17 18:12 UTC, volas commented on index.md
> +   - Оперативники режима [Ядерная Угроза](https://wiki.taucetistation.org/Syndicate_Guide) могут разрушать станцию любыми способами, но не в ущерб своей основной цели.
Потерялась причина, почему они могут это делать - я думаю, уточнение было важным. "Могут разрушать" - но это и есть их цель, акцент был на экипаже специально.

2022-02-17 18:12 UTC, volas commented on index.md
> +1. Антагонистам запрещено выжидать (кемперить) игроков в непосредственной близости к шаттлу прибытия.
Были ли прецеденты, актуально ли? Иначе это перегрузка правил и еще одно исключение, которое держать в голове. И применение со стороны администрации может быть довольно вольным.

Доки сейчас оживленная зона, рядом бар, и мы не в 2013 когда выбраться из прибытия было достижением.

2022-02-17 18:39 UTC, Lexakr commented on index.md
> +   - Оперативники режима [Ядерная Угроза](https://wiki.taucetistation.org/Syndicate_Guide) могут разрушать станцию любыми способами, но не в ущерб своей основной цели.
Они одни из немногих антагов синдиката, которые могут купить такую, например, штуку, как маяк сингулярности и выпустить ее. Наверное из "разрушать станцию" не очень очевидно, что это и про экипаж. А уточнение причины, почему они могут дестроить все на своем пути, имхо, необязательно в правилах, если есть само разрешение. Тем более, что здесь соотнести А с Б ну слишком уж просто (основная цель взорвать станцию <-> делать взрывы, убивать екипаж)

2022-02-17 18:41 UTC, Lexakr commented on index.md
> +1. Антагонистам запрещено выжидать (кемперить) игроков в непосредственной близости к шаттлу прибытия.
Прецеденты точно были, но не самое частое нарушение. В общем то бОльшая проблема это кемперство всяких ОБР, но это я даже не вносил сюда. Да, может быть и перегрузка...

2022-02-17 19:16 UTC, UDaV73rus commented on index.md
> +1. Антагонистам запрещено выжидать (кемперить) игроков в непосредственной близости к шаттлу прибытия.
> Доки сейчас оживленная зона, рядом бар, и мы не в 2013 . . .
:pepe:

2022-02-18 10:39 UTC, Lexakr commented on index.md
> +   - Даже если вы не уверены в своих силах, лучше попробовать сделать хоть что-то.
Расплывчатая формулировка убрана из пунктов правил антага. Сейчас в цитату ее вставил, просто не знаю, как выглядеть будет, если тупо текст после заголовка. Оставил, чтобы понимать суть антагонистов в игре

2022-02-18 10:40 UTC, Lexakr commented on index.md
> +1. Антагонистам запрещено выжидать (кемперить) игроков в непосредственной близости к шаттлу прибытия.
Кемперство убрал. Надеюсь, что поднятой шумихи будет и так достаточно, чтобы таким не занимались

2022-06-25 19:34 UTC, volas commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
конфликтно, нужно обсуждать. В этой формулировке как карт бланш на любое говно и никто не уйдет довольным

2022-06-25 19:36 UTC, volas commented on index.md
> +1. Если в ваши задачи не входит физическое уничтожение экипажа/станции, то подобное поведение находится под запретом. Действуйте соразмерно своим целям.
```suggestion
1. Если в ваши задачи не входит физическое уничтожение экипажа или станции, то подобное поведение находится под запретом. Действуйте в соразмерности со своими целями.
```
"в соразмерности" - моё личное предпочтение, можно и "соразмерно" оставить

2022-06-25 19:43 UTC, volas commented on index.md
> +> Помните, что цель Антагониста — сделать раунд интереснее, веселее и опаснее в разумных пределах. Постарйтесь сделать раунд более интересным, а не просто выполнить свои цели и играть дальше как ни в
```suggestion
> Помните, что цель Антагониста — сделать раунд для остального экипажа интереснее, веселее и опаснее в разумных пределах. По возможности не ограничивайтесь сухим выполнением своих задач.
```
стилистически чуть отредактировал, а то два раза сделать интереснее.

Но это тоже стоит обсудить, потому что антагонисты, пытающиеся сделать что-то "интересное", могут быть той еще головной болью для админов. И цитата конфликтует с правилами про "соразмерности" и т.д.

2022-06-25 19:44 UTC, volas commented on index.md
> +   - Антагонистам разрешено убивать или другим образом выводить других игроков из раунда, если это совершается непосредственно ради выполнения целей.
имхо лишнее, очевидно и строчкой выше и так подразумевается

2022-06-25 19:48 UTC, volas commented on index.md
> +> Помните, что цель Антагониста — сделать раунд интереснее, веселее и опаснее в разумных пределах. Постарйтесь сделать раунд более интересным, а не просто выполнить свои цели и играть дальше как ни в
Ну и про это же уже есть пункт ниже, 

> В исключительных случаях антагонисты могут отклоняться от выполнения своих целей, если это идет на пользу раунду в целом.

2022-07-13 14:03 UTC, Lexakr commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
В этом и смысл, карт бланш на любое говно, как победа в лотерею

2022-07-13 14:05 UTC, Lexakr commented on index.md
> +1. Если в ваши задачи не входит физическое уничтожение экипажа/станции, то подобное поведение находится под запретом. Действуйте соразмерно своим целям.
Слеш убрать согласен, а соразмерно целям на сколько я знаю более литературно

2022-07-13 14:15 UTC, Lexakr commented on index.md
> +> Помните, что цель Антагониста — сделать раунд интереснее, веселее и опаснее в разумных пределах. Постарйтесь сделать раунд более интересным, а не просто выполнить свои цели и играть дальше как ни в
Я не знаю, для меня не конфликтует ни с чем цитата. Если не быть злостным, то цитата трактуется не иначе как "постарайся не тупа сделать стелс-гринтекст и сидеть до конца смены, а замутить чета прикольное". гух?

2022-07-13 16:33 UTC, volas commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
Стелс выпуск форона в начале раунда вполне входит в список средств. 

У нас не так много антагов с условным карт бланшем, и все имеют свои ограничения, в частности обычно станция ставится в известность и противопоставляется антагу. Нюка - о ней экипажу известно и вся станция будет с ней бороться. Малф на последних стадиях - так же. Абоминация - так же анонсится о её присутствии всему экипажу.

Если против захвата шаттла не будет подобного, то ничего хрошего из этого не получится.

2022-07-13 16:37 UTC, volas commented on index.md
> +> Помните, что цель Антагониста — сделать раунд интереснее, веселее и опаснее в разумных пределах. Постарйтесь сделать раунд более интересным, а не просто выполнить свои цели и играть дальше как ни в
"Действуйте в соразмерности со своими целями" != антагонист, делающий что-то "веселое" вне его целей.

И это "веселое" - кто это будет определять, судить, просто еще одно минное поле для баталий на форуме.

2022-07-13 16:49 UTC, Lexakr commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
Хайджек выпадает значительно реже, чем режимные роли. Допустим, принимаю описанные претензии, но нам же нужно модерировать поведение триторов с хайджеком, ибо сейчас у многих противоположные мнения, что среди админов, что среди игроков. Можешь посмотреть на форуме что с опросом, там большинство за вседозволенность (еще бы), по крайней мере это обозначит точку в вопросе. А стелс выпуск форона в начале раунда это уже плей ту вин и наказать можно по нему (как и других спидран триторов)

2022-07-15 13:58 UTC, volas commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
У тебя тут в одном абзаце комментария рядом "вседозволенность" и "плей ту вин и бан", что-то не то.

Если задача проблемная, то можно её убрать, на самом деле.

2022-07-15 15:08 UTC, volas requested changes
в процессе обсуждения, не решенные вопросы

2022-08-31 17:57 UTC, Lexakr commented
Глянул сейчас случайно статистику по Хиджаку, у него шанс 1% приблизительно (меньше), а винрейт на первом сервере 6% (общий 12%). Дополнительно убедился, что разрешить любой щит хиджакерам это нормально и не повредит, а плеерам радость на такой редкой роли

2022-09-02 19:40 UTC, volas commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
https://github.com/TauCetiStation/TauCetiClassic/pull/9971 перенёс вопрос в сферу билда

2022-12-19 22:55 UTC, volas commented on index.md
> +   - Цель "Захватить Шаттл" означает, что вы вправе устроить на станции любой хаос, необходимый для достижения вашей цели.
Решено в https://github.com/TauCetiStation/TauCetiClassic/pull/10543

Можно убрать отдельное упоминание из этого ПР-а.

2023-03-27 19:22 UTC, Lexakr commented
@volas по-моему все спорный моменты улажены. Про конфликт цитаты с правилом соразмерности - в цитате написано "в разумных пределах", что как раз и отсылает в частности к соразмерности

2023-04-07 13:03 UTC, Lexakr commented
Еще одна итерация правок, из обсуждения с ГМами

2023-05-02 09:40 UTC, skvazarb commented on index.md
> +1. Если в ваши задачи не входит физическое уничтожение экипажа или станции, то подобное поведение находится под запретом. Действуйте соразмерно своим целям.
Текущая версия ПР-а возвращает в правила формулировки, которые относительно недавно были намеренно удалены. Соответственно это возвращает все ранее обсуждавшиеся проблемы. Чтобы не повторяться, обсуждения и комментарии можно посмотреть здесь:
https://github.com/TauCetiStation/Rules/pull/66#discussion_r495118076
https://github.com/TauCetiStation/Rules/pull/66#discussion_r495125488
https://github.com/TauCetiStation/Rules/pull/66#discussion_r961944341 (ветка)

2024-03-29 23:47 UTC, volas commented on index.md
> +> Помните, что цель Антагониста — сделать раунд веселым, опасным и захватывающим в разумных пределах. По возможности не ограничивайтесь сухим выполнением своих задач.
рассматривая еще раз, я всё же против этой цитаты. Оно не правило, ни к чему не обязывает, но может неверно трактоваться и ссылаться игроками пытающимися сделать весело в своём понимании. Просто не пренебрегать своими целями уже достаточно, и симбака сейчас все "скучные" цели и так выпиливает в пользу более интересных.

2024-03-29 23:51 UTC, volas commented
пр старый, много решено было другими способами, сейчас не уверен что есть смысл обсуждать. Если что - можно переоткрыть по новой.

2024-03-29 23:51 UTC, closed without merging