Самоантагонизм как отдельное основное правило
TauCetiStation/Rules pull request #72
Opened 2022-02-17 13:47 UTC by Lexakr

Вынес селф-антаггинг в **отдельный** пункт основных правил из правил персонажа и дополнил-уточнил. Объясняю это тем, что в наших реалиях самоантагонизм вещь во-первых очень частая, во-вторых проблемная, явно важнее какого-нибудь пункта про уважение цепи командования.

Из нового - политика использования лимиток и других бомб, устраивающих разгермы и запрет на отвлечение СБ во время прямой угрозы (действия, на которые СБухам придется отвлекаться, когда есть какая-то прямая угроза типа ксеноморфов/нюкеров и тд)

2022-02-17 16:03 UTC, Gort133 commented on index.md
> +   - Незначительная преступная деятельность разрешена, вы можете быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и т.п. Однако, придерживайтесь некоторых рамок: ваши дейст
>заниматься мелкими гражданами
???

2022-02-17 18:15 UTC, volas commented on index.md
> +   - Не вынуждайте своими действиями службу безопасности тратить на вас время и ресурсы во время наличия [прямой угрозы](https://wiki.taucetistation.org/Standard_Operating_Procedure#%D0%9A%D1%80%D0%B
```suggestion
   - Не вынуждайте своими действиями службу безопасности тратить на вас время и ресурсы во время наличия [прямой угрозы](https://wiki.taucetistation.org/Standard_Operating_Procedure#Красный_уровень_тревоги_-_прямая_угроза) на станции.
```

2022-06-25 19:15 UTC, volas commented
> Вынес селф-антаггинг в отдельный пункт основных правил из правил персонажа и дополнил-уточнил. Объясняю это тем, что в наших реалиях самоантагонизм вещь во-первых очень частая, во-вторых проблемная, явно важнее какого-нибудь пункта про уважение цепи командования.

Основные правила не то, что важнее, просто их область применения больше. Область селфантага - персонаж, а не игрок, стоит оставить там. Я вообще хотел бы разделить когда-нибудь на IC и OOC разделы... #45

2022-06-25 19:21 UTC, volas commented on index.md
> +   - Использование бомб допустимо только на полигоне или астероиде. Если вы хотите взорвать бомбу на станции по какой-либо причине, например, для уничтожения блоба или ксеноморфов, свяжитесь с Главам
"уничтожения блоба или ксеноморфов" не имеет отношения к селфантагу, а без IC-причины это очевидный гриф и отдельное правило и так. Стоит переформулировать, если бомбы тут про отыгрышь террориста - про это и написать

2022-06-25 19:23 UTC, volas commented on index.md
> +   - Незначительная преступная деятельность разрешена, вы можете быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и т.п. Однако, придерживайтесь некоторых рамок: ваши дейст
"нельзя совершаться"? Предыдущий вариант мне кажется был более емким про не то что выводить из игры, а не делать целью своих действий вывод кого-то из игры

2022-06-25 19:24 UTC, volas commented on index.md
> +   - Не вынуждайте своими действиями службу безопасности тратить на вас время и ресурсы во время наличия [прямой угрозы](https://wiki.taucetistation.org/Standard_Operating_Procedure#Красный_уровень_т
:+1:

2022-07-14 06:02 UTC, Lexakr commented on index.md
> +   - Незначительная преступная деятельность разрешена, вы можете быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и т.п. Однако, придерживайтесь некоторых рамок: ваши дейст
Но там же нет слова нельзя, там "действия не должны....совершаться"

2022-07-15 14:04 UTC, volas commented on index.md
> +   - Незначительная преступная деятельность разрешена, вы можете быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и т.п. Однако, придерживайтесь некоторых рамок: ваши дейст
С трудом вспомнил, что имел в виду. Мне первый раз почему-то показалось, что "совершаться" висит само по себе, типо
```
Однако, придерживайтесь некоторых рамок: 
(
	(ваши действия не должны затрагивать значительную часть персонала), 
	(надолго выводить кого-либо из игры), 
	(совершаться без наличия разумной IC-причины)
)
```
слишком сложное предложение.

2022-07-15 15:08 UTC, volas requested changes
в процессе обсуждения, не решенные вопросы

2022-09-01 05:24 UTC, skvazar commented
У меня есть как концептуальные так и предметные претензии к этому предложению. В целом если в каком-то сообществе сложилось использование термина самоантагонизма, это совершенно не обязательно означает, что его полезно переносить к нам, где такая практика не появилась. 

Прямо сейчас тут написано, что самоантагонизм запрещен, но нет никаких объяснений что это собственно такое, только написано что им считается кража предметов высокого риска, причем с довольно странными оговорками. Самоантагонизм не является каким-то очевидным термином, по крайней мере не для нашего сервера. Возможное преимущество могло бы состоять в появлении короткого референса на это правило, но прямо сейчас выглядит что относительно понятное и лаконичное правило было размазано какой-то водой и к нему был прилеплен непонятный термин.

По поводу обновленных формулировок прокомментирую отдельно. Если кратко то

- Надо или дать короткое определение этому самому самоантагонизму или вообще не упоминать его в правилах
- Рерайт получился скорее неудачным. Если нет хороших вариантов, лучше оставить текущую версию, она вполне сносная.
- Уточнение про красный код отличное, его однозначно следует добавить в правила.

2022-09-01 05:46 UTC, skvazarb reviewed
У меня есть как концептуальные так и предметные претензии к этому предложению. В целом если в каком-то сообществе сложилось использование термина самоантагонизма, это совершенно не обязательно означает, что его полезно переносить к нам, где такая практика не появилась. 

Прямо сейчас тут написано, что самоантагонизм запрещен, но нет никаких объяснений что это собственно такое, только написано что им считается кража предметов высокого риска, причем с довольно странными оговорками. Самоантагонизм не является каким-то очевидным термином, по крайней мере не для нашего сервера. Возможное преимущество могло бы состоять в появлении короткого референса на это правило, но прямо сейчас выглядит что относительно понятное и лаконичное правило было размазано какой-то водой и к нему был прилеплен непонятный термин.

По поводу обновленных формулировок прокомментирую отдельно. Если кратко то

- Надо или дать короткое определение этому самому самоантагонизму или вообще не упоминать его в правилах
- Рерайт получился скорее неудачным. Если нет хороших вариантов, лучше оставить текущую версию, она вполне сносная.
- Уточнение про красный код отличное, его однозначно следует добавить в правила

2022-09-01 05:46 UTC, skvazarb commented on index.md
> +   - Незначительная преступная деятельность разрешена, вы можете быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и т.п. Однако, придерживайтесь некоторых рамок: ваши дейст
> совершаться без наличия разумной IC-причины

Может работать как мина в правилах, потому что само правило хоть и построено на противопоставлении, но оно должно скорее разрешать мелкие преступления, освобождая игроков в этих случаях от допросов админов, которые начнут разбираться были ли у тебя IC-причины и достаточно они разумные или нет.

2022-09-01 05:46 UTC, skvazarb commented on index.md
> +   - Использование бомб допустимо только на полигоне или астероиде. Если вы хотите взорвать бомбу на станции по какой-либо причине, например, для уничтожения блоба или ксеноморфов, свяжитесь с Главам
Взрывы бомб действительно полностью поглощаются правилом о грифе, здесь слишком подробное уточнение отдельного вопроса.

2022-09-01 05:46 UTC, skvazarb commented on index.md
> +   - Кража [предметов высокого риска](https://wiki.taucetistation.org/High-risk_items) и других уникальных предметов, отсутствие которых может сказаться на развитии раунда, считается самоантазонизмом
Если "кража" предметов высокого риска совершается при необходимости в чрезвычайной ситуации, то может это и не самоантагонизм тогда? Текущий вариант в правилах, где акцент делается на таких предметах как на цели выглядит понятнее.

2022-09-01 05:46 UTC, skvazarb commented on index.md
> +   - Помощь антагонистам допустима, но она должна быть скорее пассивной, чем активной, и для нее нужны веские причины (открыть им шлюз или закрыть глаза на их деяния — это нормально, добровольно дать
Открыть шлюз это точно не пассивная помощь. Также под вопросом нужно ли требовать веские причины чтобы закрыть глаза на действия антагонистов, по крайней смотря на какие действия. Направление верное, но надо или упростить суть или наоборот более ясно обозначить пограничные случаи.

2022-09-01 05:46 UTC, skvazarb commented on index.md
> +   - Не вынуждайте своими действиями службу безопасности тратить на вас время и ресурсы во время наличия [прямой угрозы](https://wiki.taucetistation.org/Standard_Operating_Procedure#Красный_уровень_т
Очень удачное дополнение, следует перенести в правила в любом случае даже независимо от всех прочих изменений.

2022-09-01 06:10 UTC, Lexakr commented on index.md
> +   - Помощь антагонистам допустима, но она должна быть скорее пассивной, чем активной, и для нее нужны веские причины (открыть им шлюз или закрыть глаза на их деяния — это нормально, добровольно дать
На самом деле да, так себе формулировка, потому что во время РП революции дать бомбу чтобы ей подорвали ненавистных СБух (к примеру) это уже вроде как и нормально, а открыть шлюз пассивная - это же дефолтное действие, можно открыть типа случайно

2022-09-01 07:06 UTC, skvazarb commented on index.md
> +   - Помощь антагонистам допустима, но она должна быть скорее пассивной, чем активной, и для нее нужны веские причины (открыть им шлюз или закрыть глаза на их деяния — это нормально, добровольно дать
Если открыть шлюз кому-то, то это никак не пассивная помощь, потому что это целенаправленное действие. Открыть шлюз случайно другой случай - это случайная помощь, а не пассивная.

В целом я считаю пункт про помощь антагонистам лишним уточнением, которое и без того достаточно ясно вытекает из других правилах, но все-таки попытался переписать этот вариант на более точную формулировку

> Допускается помогать антагонистам, но ваша помощь должна быть скорее пассивной. Если ваши действия или бездействие при этом угрожают другим игрокам или станции, то у вас должны быть достаточные причины для такого поведения.

2023-03-27 19:47 UTC, Lexakr commented on index.md
> +   - Использование бомб допустимо только на полигоне или астероиде. Если вы хотите взорвать бомбу на станции по какой-либо причине, например, для уничтожения блоба или ксеноморфов, свяжитесь с Главам
Бомбы здесь в оригинале по той причине, что вне полигона и астероида они используются только антагами. Поэтому их использование не будучи антагом это селф-антаг в каком-то смысле. Возможно, это надо отправить в другое место, но сам пункт про использование лимиток обязательно нужен. Это важная, исторически закрепившаяся часть игры, но и очень неоднозначная. Ни у игроков ни даже у админов нет понимания, как и когда их можно взрывать вне полигона. Эта поправка задает пару исчерпывающих прецедентов (режимы где на кону существование станции и так) и снимает разногласия

2023-03-27 19:51 UTC, Lexakr commented on index.md
> +   - Незначительная преступная деятельность разрешена, вы можете быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и т.п. Однако, придерживайтесь некоторых рамок: ваши дейст
Не думаю, что админы начнут разбираться в наличии ИС причин по каждому чиху. Но у игрока действительно должна быть какая-то ИС мотивация грабить/брать взятки, он хотя бы должен ее придумать

2023-03-27 19:54 UTC, Lexakr commented on index.md
> +   - Кража [предметов высокого риска](https://wiki.taucetistation.org/High-risk_items) и других уникальных предметов, отсутствие которых может сказаться на развитии раунда, считается самоантазонизмом
Соглашусь

2023-03-27 19:57 UTC, Lexakr commented
> У меня есть как концептуальные так и предметные претензии к этому предложению. В целом если в каком-то сообществе сложилось использование термина самоантагонизма, это совершенно не обязательно означает, что его полезно переносить к нам, где такая практика не появилась.
> 
> Прямо сейчас тут написано, что самоантагонизм запрещен, но нет никаких объяснений что это собственно такое, только написано что им считается кража предметов высокого риска, причем с довольно странными оговорками. Самоантагонизм не является каким-то очевидным термином, по крайней мере не для нашего сервера. Возможное преимущество могло бы состоять в появлении короткого референса на это правило, но прямо сейчас выглядит что относительно понятное и лаконичное правило было размазано какой-то водой и к нему был прилеплен непонятный термин.
> 
> По поводу обновленных формулировок прокомментирую отдельно. Если кратко то
> 
> * Надо или дать короткое определение этому самому самоантагонизму или вообще не упоминать его в правилах
> * Рерайт получился скорее неудачным. Если нет хороших вариантов, лучше оставить текущую версию, она вполне сносная.
> * Уточнение про красный код отличное, его однозначно следует добавить в правила

Не согласен, что этот термин не очевидный для нашего сервера - наоборот, это то, чем игроки занимаются очень часто. А определение термина находится во втором предложении "Если игра не выдала вам роль антагониста — вы не являетесь им"

2023-04-07 13:05 UTC, Lexakr commented
Селф-антагов вернул в правила персонажа и еще пофиксил всякое

2023-05-02 10:12 UTC, volas approved these changes

2023-05-02 10:15 UTC, volas commented
текущий вариант хороший :+1:

2023-05-02 10:38 UTC, volas commented on index.md
> +1. Самоантагонизм (self-antagging) запрещен. Если игра не выдала вам роль антагониста — вы не являетесь им.
```suggestion
1. Самоантагонизм (self-antagging) запрещен — вы не являетесь антагонистом, если вам не выпала роль.
```

2024-03-29 23:29 UTC, volas commented on index.md
> +   - Использование бомб допустимо только на полигоне или астероиде. Если вы хотите взорвать бомбу на станции по какой-либо причине, например, для уничтожения блоба или ксеноморфов, свяжитесь с Главам
```suggestion
```

А еще раз посмотрел и всё же думаю, это лишнее, и если всё же надо - стоит обсудить отдельно. Взрывы это про гриф, в том числе и в случае антагов, где исключением только цель/эскалация будет. А подрывы блобов и ксеноморфов не вяжутся с селфантагом, так как действия изначально против антагонистов.

Возможно это надо отдельным правилом, поясняющим использование бомб, но это всё не в рамках текущего ПР-а.

2024-03-29 23:31 UTC, volas commented on index.md
> +   - Запрещена кража уникальных и [высокорисковых предметов](https://wiki.taucetistation.org/High-risk_items), отсутствие которых может сказаться на развитии раунда.
```suggestion
   - Вы не должны красть или выводить из игры [высокорисковые предметы](https://wiki.taucetistation.org/High-risk_items), отсутствие которых может сказаться на развитии раунда.
```

2024-03-29 23:33 UTC, merged